### ISSUE TITLE
Ignoring clocale-0.0.4 because its extensions are not built. 

### ISSUE THREAD

**Issue by dig22** [avdv/clocale#90]
Ignoring clocale-0.0.4 because its extensions are not built. Try: gem pristine clocale --version 0.0.4

**Comment by avdv** [comment]
Uh, was that a question? You did not say what you did, what you tried, only pasting some output into an issue?!

I am not able to help.

**Comment by kbrock** [comment]
Ok. so this looks like a tip for others.

If clocale gem is having problems due to the extension not being build, you can rebuild the gem using the following:

```bash
gem pristine clocale --version 0.0.4
```

Agreed, this is not an issue. so it can be closed.

**Comment by avdv** [comment]
OK, closing.
